name:                ImageCompressor
version:             0.1.0.0
github:              "EpitechPromo2027/B-FUN-400-PAR-4-2-image-compressor-michil.egorov"
license:             BSD-3-Clause
author:              "Michil Egorov"
maintainer:          "michil.egorov@epitech.eu"
copyright:           "2024 Michil Egorov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to ImagePoint users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ImageCompressor#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  imageCompressor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ImageCompressor
